name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy ruff
    
    - name: Check formatting with Black
      run: |
        black --check src tests

    - name: Check imports with isort
      run: |
        isort --check-only --profile black src tests
    
    - name: Check with Ruff
      run: |
        ruff src tests
    
    - name: Type check with mypy
      run: |
        mypy src